server {
    listen 80;
    server_name penpot.aiqadam.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name penpot.aiqadam.org;

    client_max_body_size 367001600;

    ssl_certificate /etc/letsencrypt/live/penpot.aiqadam.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/penpot.aiqadam.org/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    access_log /var/log/nginx/penpot.aiqadam.org.access.log;
    error_log  /var/log/nginx/penpot.aiqadam.org.error.log;

    location /ws/notifications {
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://localhost:9001/ws/notifications;
    }

    location /mcp/ws {
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://localhost:9001/mcp/ws;
    }

    location /mcp/stream {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://localhost:9001/mcp/stream;
    }

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect off;
        proxy_pass http://localhost:9001/;
    }
}
